Remove `devOptions.fallback` from configuration reference
After reading the configuration docs, I tried using the `devOptions.fallback` option as described, but saw the following error when starting the snowpack dev server:

```
[16:29:33] [snowpack] [v3.0] Deprecated! "devOptions.fallback" is now replaced by "routes".
More info: https://www.snowpack.dev/guides/routing
See https://www.snowpack.dev for more info.

Error: [v3.0] Deprecated! "devOptions.fallback" is now replaced by "routes".
More info: https://www.snowpack.dev/guides/routing
See https://www.snowpack.dev for more info.
    at handleDeprecatedConfigError (/Users/David/code/fast-faction/node_modules/snowpack/lib/index.js:122187:11)
    at valdiateDeprecatedConfig (/Users/David/code/fast-faction/node_modules/snowpack/lib/index.js:122234:9)
    at Object.loadConfiguration (/Users/David/code/fast-faction/node_modules/snowpack/lib/index.js:122430:5)
    at async cli (/Users/David/code/fast-faction/node_modules/snowpack/lib/index.js:183658:22)
```

I thought removing this from the docs would help others avoid the same error. Brand new to snowpack, so forgive me if I'm missing something!